//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClinica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosClinicas
    {
        public int IdUsuarioClinicas { get; set; }
        public int UserId { get; set; }
        public int IdCine { get; set; }
    
        public virtual Clinicas Clinicas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
